# Base docker build
FROM sonic-slave-bullseye:ef5a3621467

# Copy the cache data to host
From scratch as output
COPY --from=sonic-slave-bullseye:ef5a3621467 /cache.tgz cache.tgz

# Clean up the cache data
FROM sonic-slave-bullseye:ef5a3621467 as final
RUN rm /cache.tgz

