#!/bin/sh
set -e
# Automatically added by dh_elpa/UNDECLARED
if [ -e /var/lib/emacsen-common/state/package/installed/emacsen-common -a -x /usr/lib/emacsen-common/emacs-package-remove ] ; then
	/usr/lib/emacsen-common/emacs-package-remove --prerm elpa-protobuf-mode
fi
# End automatically added section
